grocery-manager:
  db-transaction-retry:
    max-attempts: 3
    initial-interval: 1000 # 1 second
    max-interval: 5000 # 5 seconds
    multiplier: 1.5
    retryable-exceptions:
      - org.springframework.dao.OptimisticLockingFailureException
      - org.springframework.dao.PessimisticLockingFailureException
      - org.springframework.dao.DataIntegrityViolationException
      - org.springframework.dao.ConcurrencyFailureException
      - org.springframework.transaction.TransactionSystemException
  schedule:
    order:
      expire:
        # Cron expression for scheduling the order expiration job
        cron: "0 * * * * ?" # Every minute
        # Expire orders that have not been paid within time
        threshold: 30m
        # Bottom threshold for limiting the query
        bottom-threshold: 4h
        # Maximum number of orders to expire in a single job run
        max-size: 1000
        # Batch size for updating orders in the database
        batch-update-size: 250
spring:
  application:
    name: grocery-manager
  security:
    provider: basic
    user:
      name: admin
      password: admin
      roles: GM_USER,GM_ADMIN
  cache:
    ttl-minutes: 20
    max-size: 10
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:grocery-manager;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  liquibase:
    database-change-log-table: GM_DATABASE_CHANGELOG
    database-change-log-lock-table: GM_DATABASE_CHANGELOG_LOCK
    url: jdbc:h2:mem:grocery-manager;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password: password
    enabled: true
    clear-checksums: true
    contexts: all
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    hibernate:
      ddl-auto: validate
  mvc:
    async:
      request-timeout: 300000 # 5 minutes
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,prometheus,env,beans,liquibase,configprops,conditions,loggers,threaddump,caches
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.95,0.99
      expiry:
        http.server.requests: 1m
springdoc:
  swagger-ui:
    path: /swagger-ui
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
server:
  error:
    include-message: always
logging:
  level:
    org.hibernate: WARN
    org.zalando.logbook: TRACE
logbook:
  write:
    max-body-size: 1024
  predicate:
    include:
      - path: /api/**