INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'MILK1', 'Whole Milk 1L', 100, 29.00, 'init_data', 'init_data');
INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'BREAD1', 'White Bread Loaf', 50, 34.00, 'init_data', 'init_data');
INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'EGGS12', 'Free Range Eggs 12pcs', 80, 69.00, 'init_data', 'init_data');
INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'APPLE1', 'Apple Golden Delicious 1kg', 120, 59.00, 'init_data', 'init_data');
INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'BANANA1', 'Banana 1kg', 110, 45.00, 'init_data', 'init_data');
INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'TOMATO1', 'Tomato Vine 500g', 90, 39.00, 'init_data', 'init_data');
INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'POTATO1', 'Potato 2kg', 60, 59.00, 'init_data', 'init_data');
INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'CARROT1', 'Carrot 1kg', 70, 29.00, 'init_data', 'init_data');
INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'CHEESE1', 'Gouda Cheese 200g', 40, 54.00, 'init_data', 'init_data');
INSERT INTO GM_PRODUCT (ID, CODE, NAME, STOCK_QUANTITY, UNIT_PRICE, CREATED_BY, UPDATED_BY)
VALUES (NEXT VALUE FOR SEQ_GM_PRODUCT, 'YOGURT1', 'Greek Yogurt 500g', 55, 42.00, 'init_data', 'init_data');
